import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  content: { paddingBottom: 32 },
  headerGradient: { paddingTop: 56, paddingHorizontal: 24, paddingBottom: 20 },
  headerTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -0.5,
  },
  headerSubtitle: { fontSize: 15, color: colors.textSecondary, marginTop: 4 },
  statsRow: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    gap: 10,
    marginBottom: 24,
  },
  statCard: { flex: 1, borderRadius: 16, overflow: 'hidden' },
  statGradient: {
    padding: 14,
    alignItems: 'center',
    gap: 4,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statValue: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
  },
  statLabel: {
    fontSize: 10,
    color: colors.textMuted,
    textAlign: 'center',
    fontWeight: '500',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 12,
    paddingHorizontal: 24,
  },
  chartCard: {
    backgroundColor: colors.bgCard,
    borderRadius: 20,
    padding: 20,
    marginHorizontal: 24,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 24,
  },
  barContainer: { marginBottom: 18 },
  barLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    alignItems: 'center',
  },
  barLabelLeft: { flexDirection: 'row', alignItems: 'center', gap: 8, flex: 1 },
  barDot: { width: 8, height: 8, borderRadius: 4 },
  materiaNome: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    flex: 1,
  },
  materiaTempo: { fontSize: 13, fontWeight: '500', color: colors.textMuted },
  barTrack: {
    height: 10,
    backgroundColor: colors.bgElevated,
    borderRadius: 5,
    overflow: 'hidden',
  },
  barFill: { height: '100%', borderRadius: 5 },
  historyCard: {
    backgroundColor: colors.bgCard,
    borderRadius: 20,
    padding: 4,
    marginHorizontal: 24,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 30,
  },
  historyItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  historyLeft: { flex: 1 },
  historyMateria: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  historyDate: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  historyBadge: {
    backgroundColor: colors.accent + '20',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  historyTime: { fontSize: 14, fontWeight: '700', color: colors.accent },
  emptyHistory: { alignItems: 'center', paddingVertical: 32, gap: 8 },
  emptyText: {
    color: colors.textMuted,
    textAlign: 'center',
    paddingVertical: 10,
    fontSize: 14,
  },
});
