import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  headerGradient: { paddingTop: 56, paddingHorizontal: 24, paddingBottom: 20 },
  headerTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: 15,
    color: colors.textSecondary,
    marginTop: 4,
  },
  daysScroll: { maxHeight: 56, marginTop: 8 },
  daysRow: { paddingHorizontal: 16, gap: 8 },
  dayChip: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.border,
    minWidth: 52,
  },
  dayChipActive: {
    backgroundColor: colors.primary + '25',
    borderColor: colors.primary,
  },
  dayLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  dayLabelActive: { color: colors.primary },
  dayBadge: {
    marginTop: 4,
    backgroundColor: colors.bgElevated,
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 1,
  },
  dayBadgeActive: { backgroundColor: colors.primary + '40' },
  dayBadgeText: { fontSize: 10, fontWeight: '700', color: colors.textMuted },
  dayBadgeTextActive: { color: colors.primaryLight },
  summaryRow: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    gap: 12,
    marginTop: 16,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: colors.bgCard,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    gap: 4,
  },
  summaryValue: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
  },
  summaryLabel: { fontSize: 12, color: colors.textMuted },
  lista: { flex: 1, marginTop: 16 },
  listaContent: { paddingHorizontal: 24, paddingBottom: 100 },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 48,
    gap: 8,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
    marginTop: 8,
  },
  emptyText: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 24,
  },
  horarioCard: {
    flexDirection: 'row',
    backgroundColor: colors.bgCard,
    borderRadius: 16,
    marginBottom: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
  },
  corBarra: { width: 4 },
  horarioContent: { flex: 1, padding: 16 },
  horarioTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  horarioHora: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.text,
    fontVariant: ['tabular-nums'],
  },
  horarioDuracao: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.primaryLight,
    backgroundColor: colors.primary + '20',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  horarioMateria: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.textSecondary,
    marginTop: 6,
  },
  horarioFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
  },
  notifRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  notifText: { fontSize: 12, color: colors.textMuted },
  acoesRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    borderRadius: 28,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  fabGradient: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.bgCard,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
    maxHeight: '90%',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.text,
  },
  modalDia: {
    fontSize: 14,
    color: colors.primaryLight,
    marginTop: 4,
    marginBottom: 20,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
    marginTop: 12,
  },
  materiasScroll: { marginBottom: 4 },
  materiaChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 8,
    backgroundColor: colors.bgElevated,
  },
  materiaChipText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.textSecondary,
  },
  textInput: {
    backgroundColor: colors.bgElevated,
    borderRadius: 12,
    padding: 14,
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
    borderWidth: 1,
    borderColor: colors.border,
    fontVariant: ['tabular-nums'],
  },
  presetRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  presetChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: colors.bgElevated,
    borderWidth: 1,
    borderColor: colors.border,
  },
  presetChipActive: {
    backgroundColor: colors.primary + '25',
    borderColor: colors.primary,
  },
  presetText: { fontSize: 14, fontWeight: '500', color: colors.textSecondary },
  presetTextActive: { color: colors.primaryLight },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    paddingVertical: 8,
  },
  switchLabel: { fontSize: 16, color: colors.text, fontWeight: '500' },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 24,
  },
  btnCancelar: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: colors.bgElevated,
    alignItems: 'center',
  },
  btnCancelarText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  btnSalvar: { flex: 1, borderRadius: 14, overflow: 'hidden' },
  btnSalvarGradient: {
    paddingVertical: 14,
    alignItems: 'center',
  },
  btnSalvarText: { fontSize: 16, fontWeight: '600', color: '#FFF' },
});
