import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  content: { paddingBottom: 32 },
  headerGradient: { paddingTop: 56, paddingHorizontal: 24, paddingBottom: 16 },
  headerTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -0.5,
  },
  headerSubtitle: { fontSize: 15, color: colors.textSecondary, marginTop: 4 },
  materiasScroll: { marginTop: 8 },
  materiasRow: { paddingHorizontal: 24, gap: 8 },
  materiaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bgCard,
    gap: 8,
  },
  materiaDot: { width: 8, height: 8, borderRadius: 4 },
  materiaChipText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.textSecondary,
    maxWidth: 120,
  },
  addChip: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.primary + '50',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  timerWrapper: { alignItems: 'center', marginVertical: 28 },
  timerRingOuter: {
    width: 260,
    height: 260,
    borderRadius: 130,
    borderWidth: 3,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  timerRingProgress: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 130,
    borderWidth: 3,
    transform: [{ rotate: '-90deg' }],
  },
  timerCircle: {
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: colors.bgCard,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  timerText: {
    fontSize: 52,
    fontWeight: '200',
    color: colors.text,
    fontVariant: ['tabular-nums'],
    letterSpacing: 2,
  },
  timerLabel: {
    fontSize: 14,
    color: colors.textMuted,
    marginTop: 4,
    fontWeight: '500',
  },
  presetRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 24,
  },
  presetChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.border,
  },
  presetChipActive: {
    backgroundColor: colors.primary + '25',
    borderColor: colors.primary,
  },
  presetText: { fontSize: 14, fontWeight: '600', color: colors.textSecondary },
  presetTextActive: { color: colors.primaryLight },
  customTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginTop: 12,
  },
  input: {
    backgroundColor: colors.bgCard,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    width: 60,
    textAlign: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  inputUnit: { fontSize: 14, color: colors.textMuted },
  controls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    marginTop: 28,
    paddingHorizontal: 24,
  },
  btnSecondary: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.bgCard,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  btnPrimaryWrap: { borderRadius: 32, overflow: 'hidden' },
  btnPrimary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 36,
    paddingVertical: 16,
    borderRadius: 32,
  },
  btnPrimaryText: { fontSize: 18, fontWeight: '700', color: '#FFF' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.bgCard,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 16,
  },
  textInput: {
    backgroundColor: colors.bgElevated,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: colors.text,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 20,
  },
  modalButtons: { flexDirection: 'row', gap: 12 },
  btnCancelar: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: colors.bgElevated,
    alignItems: 'center',
  },
  btnCancelarText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  btnSalvarWrap: { flex: 1, borderRadius: 14, overflow: 'hidden' },
  btnSalvar: { paddingVertical: 14, alignItems: 'center' },
  btnSalvarText: { fontSize: 16, fontWeight: '600', color: '#FFF' },
});
